version: '3'
services:
  web:
    image: nginx
    volumes:
     - ./compose/nginx.conf:/etc/nginx/conf.d/default.conf
     - ./docker-data/public-files:/var/www/html/files
     - ./docker-data/assets:/var/www/html/assets

     # to prevent 404
     - /dev/null:/var/www/html/index.php
    ports:
     - "80:80"
     - "443:443"
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80
    depends_on:
      - mapas
    links:
      - mapas

  mapas:
    build:
      context: .
      dockerfile: ./compose/Dockerfile

    ports:
      - "9000:9000"
    volumes:
      - ./themes/IberCulturaViva:/var/www/html/protected/application/themes/IberCulturaViva
      - ./compose/config.d:/var/www/html/protected/application/conf/config.d

      # o usuário www-data dentro do container precisa ter permissão de escrita nessas 3 pastas abaixo
      - ./docker-data/assets:/var/www/html/assets
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/private-files:/var/www/private-files

      - ./conf/agent-types.php:/var/www/html/protected/application/conf/agent-types.php
      - ./conf/opportunity-types.php:/var/www/html/protected/application/conf/opportunity-types.php
      - ./conf/taxonomies.php:/var/www/html/protected/application/conf/taxonomies.php
      - ./translations/es_ES.mo:/var/www/html/protected/application/translations/es_ES.mo
      - ./translations/es_ES.po:/var/www/html/protected/application/translations/es_ES.po
      - ./translations/pt_BR.mo:/var/www/html/protected/application/translations/pt_BR.mo
      - ./translations/pt_BR.po:/var/www/html/protected/application/translations/pt_BR.po

    links:
      - db
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas

      - APP_LCODE=es_ES,pt_BR

      - APP_MODE=development
      - SLIM_DEBUG=true
      - ACTIVE_THEME=IberCulturaViva

      - GOOGLE_GEOCODING_API_KEY=AIzaSyCkHK9L03_cQZLy8TM8O0YgDmAGWLGPbgk

    depends_on:
      - db

  db:
    image: mdillon/postgis:10
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
      - POSTGRES_DB_TEST=mapasculturais_test
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/0.schema.sql
      - ./db/initial-data.sql:/docker-entrypoint-initdb.d/1.data.sql
